### ISSUE TITLE
sql-init assumes starting new bitcoind

### ISSUE THREAD

**Issue by dabura667** [neocogent/sqlchain#4]
I have bitcoind running under my user everytime I boot my PC, I would like to add sqlchain on top of it, but it seems to assume I've never run bitcoin.

There should be a simple question: "Do you already run bitcoin?" "Under what user?" "What's your rpc username and password?" etc.

**Comment by mewald55** [comment]
Edit: I totally misunderstood what you were requesting, ignore this!

You should only run sqlchain-init one time to setup the system configuration. After initial setup, you run ./sqlchaind to start it.

As an example, your ubuntu 16 systemd service file should look like this:
```
[Unit]
Description=sqlChain - Bitcoin SQL layer and API

[Service]
ExecStart=/sbin/start-stop-daemon --start --pidfile /var/data/sqlchain/daemon.pid --exec /usr/local/bin/sqlchaind -- /etc/bitcoin/sqlchaind.cfg

[Install]
WantedBy=multi-user.target
```

**Comment by neocogent** [comment]
If you already run bitcoin as a existing user you can just answer the questions with current values and it should work ok. It won't remove the user if it exists, though it may give an error. I'll have a look at that and see if I can make it output an "already exists" msg. 

For rpc/user password I'll have a look at improving choices there.

**Comment by neocogent** [comment]
I've pushed some changes to sqlchain-init now. It asks if you want to use existing RPC user/pwd and reads current values in bitcoin.conf for use by sqlchain. As for user to run bitcoind and sqlchain it already checked if exists so I left as is. 

I made a few other changes to services and boot enable/disable method. I wasn't able to test on systemd yet but next time I set up on a vps I'll make sure it didn't break it.

Also now asks if sig/witness data should be discarded and sets cfg value.

If you test this and it's ok, please let me know and I'll close the issue.

**Comment by neocogent** [comment]
Closing issue. Update tested on vultr instance under Ubuntu 16.04.
Thx for bringing to my attention.
