### ISSUE TITLE
./sqlchaind err

### ISSUE THREAD

**Issue by yiyiyaya** [neocogent/sqlchain#5]
Hello

## problem：
I ran the ./sqlchaind , something went wrong：
 File "./sqlchaind", line 437, in <module>
    with file(pidpath,'w') as f: 
IOError: [Errno 13] Permission denied: u'/home/shaogj/btbwork/goproj/sqlchain-master/daemon.pid'

**Comment by mewald55** [comment]
Hello,

It looks like your linux user does not have permissions to open that file.

Are you directly starting sqlchain by executing  './sqlchaind'  ?
The normal way to start sqlchaind is by using upstart or systemctl ( above ubuntu 14). You can find those commands in the [INSTALL.md guide.](https://github.com/neocogent/sqlchain/blob/304698d86861378b1108392e95e990b2ab36fce4/INSTALL.md)

If that doesn't fix the issue, I think you will need to look at the full file path to the daemon.pid file, and make sure your linux user has read+write permissions for each folder in the path.

**Comment by neocogent** [comment]
Yes, definitely related to user permissions. In this case the daemon is writing out it's process id and cannot open the file it wants to write it in.

Also, the sqlchaind daemon should be run with a cfg file. I'm not sure if you did that but didn't show it above or just didn't use a cfg. If you don't provide a cfg file it will use defaults built in. Those may be adequate for debugging (with -d) but not much good for normal use. The cfg tells it all the details about how you want to to run. You can create one manually but ideally you would use sqlchain-init to create it as it makes sure it matches properly with database and bitcoind, and is also simpler. The install guide takes you step by step through setting up as a daemon that (optionally) can start at boot as well.

**Comment by yiyiyaya** [comment]
Thank you very much, the problem has been effectively resolved @mewald55 @neocogent
